version: "3"

services:
  # front:
  #   build: ./frontend
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  #   depends_on:
  #     - back
  #   networks:
  #     - backend

  back:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}?schema=public
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    networks:
      - backend
      - dbnet

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - dbnet
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend: {}
  dbnet: {}

volumes:
  db-data: